//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqLiteCodeFirstSample.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster_
    {
        public long ID { get; set; }
        public long EmpName_ { get; set; }
        public long Salary_ { get; set; }
        public string Designation_ { get; set; }
    }
}
